name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  reviewdog-github-check:
    name: reviewdog (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: Setup reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
          chmod +x ./bin/reviewdog

      - name: Run reviewdog
        run: |
          ./bin/reviewdog -reporter=github-check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
